---
AWSTemplateFormatVersion: '2010-09-09'
Description: DataEngineering IAM Policies

Conditions:

  DataEngineeringAccounts:
    Fn::Or:
      - Fn::Equals: [ Ref: 'AWS::AccountId', '23432' ] # nonprod-auto

Mappings:
  # Account: Nonprod Automated
  "1232":
    ap-southeast-1:
      S3KmsKeyArn: arn:aws:kms:ap-southeast-1:1232:key/3136e26c-8052-432a-b1a2-fb422b8ad29a

Resources:

  ##########
  # DataEngineering Team IAM Roles
  ##########

  ##########
  # Lambda Special Privileges
  ##########

  DataEngineeringLambdaRole:
    Type: AWS::IAM::Role
    Condition: DataEngineeringAccounts
    Properties:
      RoleName: DataEngineeringLambdaPrivilegedRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

  DataEngineeringGlueRole:
    Type: AWS::IAM::Role
    Condition: DataEngineeringAccounts
    Properties:
      RoleName: DataEngineeringGlueRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole

  DataEngineeringRedshiftSpectrumRole:
    Type: AWS::IAM::Role
    Condition: DataEngineeringAccounts
    Properties:
      RoleName: DataEngineeringRedshiftSpectrumRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - redshift.amazonaws.com
            Action:
              - sts:AssumeRole

  DataEngineeringSaaRecommenderRole:
    Type: AWS::IAM::Role
    Condition: DataEngineeringAccounts
    Properties:
      RoleName: DataEngineeringSaaRecommenderRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  DataEngineeringMlFrameworkRole:
    Type: AWS::IAM::Role
    Condition: DataEngineeringAccounts
    Properties:
      RoleName: DataEngineeringMlFrameworkRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  DataEngineeringAirflowRole:
    Type: AWS::IAM::Role
    Condition: DataEngineeringAccounts
    Properties:
      RoleName: DataEngineeringAirflowRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole


  DataEngineeringLambdaPrivilegedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringLambdaPrivilegedPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - glue:*
              - cloudwatch:*
              - lambda:*
              - athena:*
              - events:*
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource:
              - !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", S3KmsKeyArn ]
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - Fn::Sub: "arn:aws:iam::${AWS::AccountId}:role/DataEngineeringGlueRole"
      Roles:
        - Ref: DataEngineeringLambdaRole

  DataEngPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: DataEngineeringPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:DescribeStackResources
            Resource:
              - Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/de-*
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:DeleteObject
            Resource:
              - arn:aws:s3:::de-data-*/*
              - arn:aws:s3:::de-data-*
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketAcl
              - s3:ListAllMyBuckets
            Resource:
              - arn:aws:s3:::de-data-*
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource:
              - !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", S3KmsKeyArn ]

  DataEngineeringGluePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringGluePolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - glue:*
            - s3:GetBucketLocation
            - s3:ListBucket
            - s3:ListAllMyBuckets
            - s3:GetBucketAcl
            - ec2:DescribeVpcEndpoints
            - ec2:DescribeRouteTables
            - ec2:CreateNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeSecurityGroups
            - ec2:DescribeSubnets
            - ec2:DescribeVpcAttribute
            - iam:ListRolePolicies
            - iam:GetRole
            - iam:GetRolePolicy
            - cloudwatch:PutMetricData
          Resource:
            - "*"
        - Effect: Allow
          Action:
            - s3:CreateBucket
          Resource:
            - arn:aws:s3:::aws-glue-*
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::aws-glue-*/*
            - arn:aws:s3:::*/*aws-glue-*/*
            - arn:aws:s3:::de-data*
            - arn:aws:s3:::de-data*/*
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::crawler-public*
            - arn:aws:s3:::aws-glue-*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - arn:aws:logs:*:*:/aws-glue/*
        - Effect: Allow
          Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:DescribeKey
            - kms:GenerateDataKey*
            - kms:ReEncrypt*
          Resource:
            - !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", S3KmsKeyArn ]
        - Effect: Allow
          Action:
            - ec2:CreateTags
            - ec2:DeleteTags
          Condition:
            ForAllValues:StringEquals:
              aws:TagKeys:
              - aws-glue-service-resource
          Resource:
            - arn:aws:ec2:*:*:network-interface/*
            - arn:aws:ec2:*:*:security-group/*
            - arn:aws:ec2:*:*:instance/*
        - Effect: Allow
          Action:
            - iam:PassRole
          Resource:
            - Fn::Sub: "arn:aws:iam::${AWS::AccountId}:role/DataEngineeringGlueRole"
      Roles:
        - Ref: DataEngineeringGlueRole

  DataEngineeringRedshiftSpectrumPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringRedshiftSpectrumPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - glue:CreateDatabase
              - glue:DeleteDatabase
              - glue:GetDatabase
              - glue:UpdateDatabase
              - glue:CreateTable
              - glue:DeleteTable
              - glue:BatchDeleteTable
              - glue:UpdateTable
              - glue:GetTable
              - glue:GetTables
              - glue:BatchCreatePartition
              - glue:CreatePartition
              - glue:DeletePartition
              - glue:BatchDeletePartition
              - glue:UpdatePartition
              - glue:GetPartition
              - glue:GetPartitions
              - glue:BatchGetPartition
            Resource:
              - "*"
      Roles:
        - Ref: DataEngineeringRedshiftSpectrumRole

  DataEngineeringSaaRecommenderPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringSaaRecommenderPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ec2:DescribeInstances
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - ec2:StartInstances
              - ec2:StopInstances
            Resource:
              - arn:aws:ec2:*:*:instance/*
            Condition:
              StringEquals:
                ec2:ResourceTag/Portfolio: de
                ec2:ResourceTag/App: saarecommender
      Roles:
        - Ref: DataEngineeringSaaRecommenderRole


  DataEngineeringMlFrameworkPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringMlFrameworkPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ec2:DescribeInstances
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - ec2:StartInstances
              - ec2:StopInstances
            Resource:
              - arn:aws:ec2:*:*:instance/*
            Condition:
              StringEquals:
                ec2:ResourceTag/Portfolio: de
      Roles:
        - Ref: DataEngineeringMlFrameworkRole

  DataEngineeringGlueZeppelinPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringGlueZeppelinPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - glue:UpdateDevEndpoint
              - glue:GetDevEndpoint
            Resource:
              - "*"

  DataEngineeringAirflowPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringAirflowPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ec2:DescribeInstances
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - ec2:StartInstances
              - ec2:StopInstances
            Resource:
              - arn:aws:ec2:*:*:instance/*
            Condition:
              StringEquals:
                ec2:ResourceTag/Portfolio: de
          - Effect: Allow
            Action:
              - sqs:ListQueues
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - glue:GetJob
              - glue:GetJobRun
              - glue:GetJobRuns
              - glue:GetJobs
              - glue:StartJobRun
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - glue:GetCrawler
              - glue:GetCrawlers
              - glue:GetCrawlerMetrics
              - glue:StartCrawler
              - glue:GetPartition
              - glue:GetPartitions
              - glue:GetDatabase
              - glue:GetDatabases
              - glue:GetTable
              - glue:GetTables
              - glue:GetTableVersions
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - sns:ListTopics
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - sns:Publish
            Resource:
              - arn:aws:sns:*:*:sia-de-etljob
              - arn:aws:sns:*:*:sia-de-sar-missing-files
      Roles:
        - Ref: DataEngineeringAirflowRole



  DataEngineeringMlAutoServicePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringMlAutoServicePolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
            - sagemaker:ListEndpoints
            - sagemaker:InvokeEndpoint
            - sagemaker:DescribeEndpoint
            Resource:
            - "*"
          - Effect: 'Allow'
            Action: 
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            Resource: 
            - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/de-mlauto-*"
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource:
              - !FindInMap [ !Ref "AWS::AccountId", !Ref "AWS::Region", S3KmsKeyArn ]


  DataEngineeringMlAutoPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringMlAutoPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:DeleteObject
            Resource:
              - arn:aws:s3:::de-mlauto-de-*/*
              - arn:aws:s3:::de-mlauto-de-*
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketAcl
              - s3:ListAllMyBuckets
            Resource:
              - arn:aws:s3:::de-mlauto-de-*
          - Effect: Allow ## Allow access to EIM2.0 data for model training 
            Action:
              - sts:AssumeRole
            Resource:
              - "arn:aws:iam::234:role/S3-1232-de-data-master-lake-redshift-allpath"

  DataEngineeringDemoMlAutoPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringDemoMlAutoPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:DeleteObject
              - s3:CopyObject
            Resource:
              - arn:aws:s3:::de-mlauto-de-demomlauto-*/*
              - arn:aws:s3:::de-mlauto-de-demomlauto-*
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketAcl
              - s3:ListAllMyBuckets
            Resource:
              - arn:aws:s3:::de-mlauto-de-demomlauto-*


  DataEngineeringMlAutoExternalKmsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringMlAutoExternalKmsPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:DescribeKey
              - kms:GenerateDataKey*
              - kms:ReEncrypt*
            Resource:
              - arn:aws:kms:ap-southeast-1:1232:key/c3d7922d-3ee2-4ab6-8023-874977650856 #ERICML APPLICATION


  DataEngineeringSagemakerMonitoringPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: DataEngineeringAccounts
    Properties:
      ManagedPolicyName: 'DataEngineeringSagemakerMonitoringPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sagemaker:Describe*
              - sagemaker:List*
            Resource:
              - "*"



